# Generated by Django 5.0.6 on 2024-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, verbose_name='Url')),
                ('username', models.TextField(blank=True, verbose_name='Username')),
                ('password', models.TextField(blank=True, verbose_name='Password')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added Date')),
                ('source', models.TextField(blank=True, null=True, verbose_name='Data Source')),
            ],
        ),
    ]
