# Generated by Django 5.0.6 on 2024-10-14 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combosearcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsFolderPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.TextField(blank=True, verbose_name='Folder Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='SearchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField(blank=True, verbose_name='Search term')),
                ('submitted_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Search Submitted Time')),
                ('search_status', models.TextField(blank=True, verbose_name='Search Status')),
                ('search_completed_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Search Completed Time')),
                ('run_time', models.FloatField(blank=True, null=True, verbose_name='Search Run Time')),
                ('total_found', models.IntegerField(blank=True, null=True, verbose_name='Total Found Results')),
                ('submitted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who submitted the request')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_string', models.TextField(blank=True, verbose_name='Found Combo')),
                ('found_in_file', models.TextField(blank=True, verbose_name='Found in File')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combosearcher.searchprogress', verbose_name='Search ID from progress')),
            ],
        ),
    ]
